spring:
  application:
    name: cloud-office-eureka
server:
  port: 9001
eureka:
  instance:
    hostname: localhost
  server:
    enableSelfPreservation: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
debug: true

from: 111
